spring:
  datasource:
    url: jdbc:mysql://dev.2boss.cn:3308/sHouseApp_pre?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: wudi
    password: 6trdHSfTcba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: redis.localdomain
    port: 6379
    password: cgwang
    database: 1
    timeout: 3000
dubbo:
  registry:
    protocol: zookeeper
    address: zk1.tuboshi.co:2181,zk2.tuboshi.co:2181,zk3.tuboshi.co:2181,zk4.tuboshi.co:2181,zk5.tuboshi.co:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    version: 1.0.0



elasticjob:
  registry:
    address: zk1.test.tuboshi.co:2181,zk2.test.tuboshi.co:2181,zk3.test.tuboshi.co:2181
    namespace: elastic-log

tokenJob:
  cron: 0 0 0/2 * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

sampleJob:
  cron: 0 0 0/2 * *  ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou


user-auth:
  expire-in:
    verification-code: 300
  jwt:
    tokenExpirationTime: 30000 # Number of minutes 默认access token过期时间,默认20天
    refreshTokenExpTime: 60000 # Minutes 默认的refresh token过期时间，默认40天
    tokenIssuer: http://liyou.co
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus





